version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "
      npm run build &&
      npm run start
      "
    ports:
      - "3095:3000"
    environment:
      - TZ=Asia/Tashkent


